Toaster notifications and relaxed URL/email validation
PolymathNetwork/polymath-ui-archived pull request #1
Opened 2018-03-16 21:19 UTC by AdamDanielKing

Changes:
- Adds Toaster and ToasterContainer for showing notifications.
- Relaxes URL and email validation.
- Adds SCSS and commands for compiling SCSS and JS.
- Adds eslint-plugin-react.
- Moves from babel-preset-es2015 to babel-preset-env.
- Adds licence to package.json.
- Adds to README.md slightly.

2018-03-19 10:17 UTC, bshevchenko requested changes

2018-03-19 10:17 UTC, bshevchenko commented on .eslintrc
> +    "plugin:react/recommended",
When you need react eslint rules use eslint-plugin-polymath-react

2018-03-19 10:17 UTC, bshevchenko commented on src/components/toaster.js
> +  show (toast, duration = 4000) {
Don't pack arguments into the one Object variable. It makes interface unclear and requires additional types specification from each user (see https://github.com/PolymathNetwork/polymath-issuer/pull/1/files#diff-ac3c50ae15a631981374f09a64815339R34).
Instead we can use extra class like – https://github.com/PolymathNetwork/polymath-issuer/commit/ea6d7f1d496476be4598437266976e7cd2249e51#diff-96547c5732d1f2950d1f0f434eeb6796R20 – or just spread and specify Flow type for each of them.

2018-03-19 10:17 UTC, bshevchenko commented on src/components/toaster.js
> +export const ToasterContainer = ({ children }) => (
Why do we need this extra component?

2018-03-19 18:20 UTC, AdamDanielKing commented on src/components/toaster.js
> +export const ToasterContainer = ({ children }) => (
The only reason for that container is to contain the toaster in something with the pui-toaster-container class. We could export the class name instead. What do you suggest?

2018-03-20 08:20 UTC, bshevchenko commented on src/components/toaster.js
> +export const ToasterContainer = ({ children }) => (
See review https://github.com/PolymathNetwork/polymath-issuer/pull/1

2018-03-22 10:57 UTC, bshevchenko requested changes

2018-03-22 10:57 UTC, bshevchenko commented on flow-typed/npm/style-loader_vx.x.x.js
> +// flow-typed signature: f47a71cb085178a55158a08fcac0a670
Are you sure that all these flow-typed/npm files should be placed in the repository?

2018-03-22 10:57 UTC, bshevchenko commented on src/components/toaster.js
> +// @flow
I think we can omit this tag everywhere

2018-03-23 22:09 UTC, merged