Add ticker, rate props to STOStatus component and logo prop to NavBar component
PolymathNetwork/polymath-ui-archived pull request #10
Opened 2018-04-25 00:23 UTC by sajclarke

Submitting changes to facilitate the design for STO Overview.

1. Added ticker and rate props to STOStatus component
2. Added optional logo prop to NavBar component

2018-04-25 11:57 UTC, bshevchenko requested changes

2018-04-25 11:57 UTC, bshevchenko commented on src/PolymathUI.js
> +};
We don't use semicolons at all. It's weird that eslint missed that here. Could you please check why?

2018-04-25 11:57 UTC, bshevchenko commented on src/PolymathUI.js
> -
I add sometimes empty string after class or function title to make code more readable.

2018-04-25 11:57 UTC, bshevchenko commented on src/components/Navbar.js
> +    // const company_logo = logo;
rubbish

2018-04-25 11:57 UTC, bshevchenko commented on src/components/Navbar.js
> +            {/* <img src={polyLogo} alt="Polymath Test" /> */}
rubbish

2018-04-25 11:57 UTC, bshevchenko commented on src/style.scss
> +@import "node_modules/carbon-components/src/globals/scss/styles.scss";
single quotes preferred

2018-04-25 17:58 UTC, sajclarke commented on src/components/Navbar.js
> +    // const company_logo = logo;
Ah I should've removed the commented code. Are you disagreeing with adding these new props as well?

2018-04-25 17:58 UTC, sajclarke commented on src/components/Navbar.js
> +            {/* <img src={polyLogo} alt="Polymath Test" /> */}
Sorry. I should've removed this comment. It was indeed left-over rubbish lol

2018-04-25 17:58 UTC, sajclarke commented
Implemented changes. I'm not sure my VSCode's eslint plugin has been causing some of the issues but that may the cause. Quick research indicates some disagreements between whether or not semi-colons should be enforced or not.

2018-04-25 17:59 UTC, sajclarke commented on src/PolymathUI.js
> +};
I think a local plugin may have been interfering but it doesn't seem the standards are strict about the use of semi-colons

2018-04-25 17:59 UTC, sajclarke commented on src/PolymathUI.js
> -
Understood. Reverted

2018-04-26 08:25 UTC, bshevchenko requested changes

2018-04-26 08:25 UTC, bshevchenko commented on src/PolymathUI.js
> +};
@sajclarke no, it's just that current eslint settings allows to use semicolons at the end of the flow type definition. Please find correct rule to forbid them from everywhere. And make sure that you chose correct repo for this (eslint-plugin-polymath or eslint-plugin-polymath-react), since for some reason I had to add max-len rule to both of these repositories, otherwise eslint-plugin-polymath-react just ignores it.

2018-04-30 04:45 UTC, bshevchenko commented
@sajclarke and please title your PRs properly

2018-05-02 00:23 UTC, sajclarke reviewed
Completed

2018-05-03 06:21 UTC, bshevchenko approved these changes

2018-05-03 06:21 UTC, merged