Add support for "-" and "." in ticker symbol
PolymathNetwork/polymath-ui-archived pull request #26
Opened 2018-06-20 14:51 UTC by sajclarke

Fix UI: Add support for "-" and "." in addition to letters and numbes in the Token Symbol

2018-06-20 15:26 UTC, bshevchenko requested changes

2018-06-20 15:26 UTC, bshevchenko commented on src/validate.js
> +  value && !/^[a-z0-9./-]+$/i.test(value) ? 'Invalid characters.' : null
you should create separate validator for this. alphanumeric means only letters and numbers

2018-06-23 12:34 UTC, sajclarke commented on src/validate.js
> +  value && !/^[a-z0-9./-]+$/i.test(value) ? 'Invalid characters.' : null
Fixed

2018-06-27 16:34 UTC, bshevchenko requested changes

2018-06-27 16:34 UTC, bshevchenko commented on src/validate.js
> +export const regex = (expr: any, value: ?string, error_msg: string) =>
We don't use snake case for variables names...
It (and a lot of other code style remarks) was already mentioned in the previous PRs many times...
If you don't have enough attention to notice such things, then at least add necessary rules to our eslint plugins

2018-06-27 16:48 UTC, sajclarke commented on src/validate.js
> +export const regex = (expr: any, value: ?string, error_msg: string) =>
Fixed

2018-06-28 07:54 UTC, bshevchenko requested changes

2018-06-28 07:54 UTC, bshevchenko commented on src/validate.js
> +export const regex = (expr: any, value: ?string, errorMessage: string) =>
expr should be RegExp, not any

2018-06-28 07:54 UTC, closed without merging