Update styles for toast notification
PolymathNetwork/polymath-ui-archived pull request #28
Opened 2018-06-22 11:53 UTC by sajclarke

Update styles for Toast notification:
1. Change green accent color to #00AA5E
2. Change font to Overpass

2018-06-22 12:56 UTC, bshevchenko requested changes

2018-06-22 12:56 UTC, bshevchenko commented on src/style.scss
> + */
we already have TOASTER section above. please put this code there

2018-06-22 12:56 UTC, bshevchenko commented on src/style.scss
> +  font-family: 'Overpass', serif !important;
use $font variable instead

2018-06-22 15:07 UTC, sajclarke commented on src/style.scss
> + */
Fixed

2018-06-22 15:07 UTC, sajclarke commented on src/style.scss
> +  font-family: 'Overpass', serif !important;
Fixed

2018-06-27 16:36 UTC, bshevchenko requested changes

2018-06-27 16:36 UTC, bshevchenko commented on src/style.scss
> +
excess empty line

2018-06-27 16:51 UTC, sajclarke commented on src/style.scss
> +
Removed

2018-06-28 08:10 UTC, merged