paused bar
PolymathNetwork/polymath-ui-archived pull request #48
Opened 2018-08-02 19:54 UTC by JoseMiguelHerrera

Added paused bar for when the token transfers are paused

fixed a typo (missed a space)

2018-08-03 08:44 UTC, bshevchenko requested changes

2018-08-03 08:44 UTC, bshevchenko commented on src/components/PausedBar.js
> +class PausedBar extends Component<Props> {
we don't need this in polymath-ui

2018-08-03 14:00 UTC, JoseMiguelHerrera commented on src/components/PausedBar.js
> +class PausedBar extends Component<Props> {
Can you elaborate what you mean by 'this'?

2018-08-14 09:37 UTC, bshevchenko approved these changes

2018-08-14 09:38 UTC, merged