Add "Raise in POLY/ETH" to STOStatus Component
PolymathNetwork/polymath-ui-archived pull request #5
Opened 2018-04-14 22:23 UTC by sajclarke

Added missing element from Stan's design for the STOStatus component

2018-04-16 07:55 UTC, bshevchenko requested changes

2018-04-16 07:55 UTC, bshevchenko commented on src/components/STOStatus.js
> +            isPolyFundraise: boolean,
What is going on with spaces here? :)

2018-04-20 07:04 UTC, bshevchenko requested changes

2018-04-20 07:04 UTC, bshevchenko commented on src/components/STOStatus.js
> +            <h3 id='pui-sto-status-title' className='bx--type-beta'>{title} <span className='bx--tag bx--tag--ibm'>Raise in {symbol}</span></h3>
There is no "Raise in..." tag on invision: https://projects.invisionapp.com/d/main#/console/13399886/287309982/preview
And btw tag for ETH should be purple and tag for POLY should be blue: https://projects.invisionapp.com/d/main#/console/13399886/287309985/preview

2018-04-20 07:40 UTC, sajclarke commented on src/components/STOStatus.js
> +            <h3 id='pui-sto-status-title' className='bx--type-beta'>{title} <span className='bx--tag bx--tag--ibm'>Raise in {symbol}</span></h3>
Ah, the design has changed since I made this pull request so no longer relevant

2018-04-20 07:44 UTC, closed without merging